openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: Learning api
  termsOfService: https://www.example.com/
  contact:
    email: mittalv3@gmail.com
    name: Vikas Mittal
    url: https://www.example.com/contacts
  license:
    name: My License
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api/
    variables: {}
    description: My fake github server
paths:
  /users:
    summary: users path level operations
    description: returns users from server, create a user, update or delete it.
    get:
      summary: fetch users from server
      description: return users
      operationId: fetchUsers
      responses:
        default:
          description: Default error sample response
      tags:
       - users
  /attempts:
    summary: attempts path level operations
    description: returns attempts from server, create a attempt, update or delete it.
    get:
      summary: fetch attempts from server
      description: return attempts
      operationId: fetchAttempts
      responses:
        default:
          description: Default error sample response
      tags:
       - attempts
