openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: Learning api
  termsOfService: https://www.example.com/
  contact:
    email: mittalv3@gmail.com
    name: Vikas Mittal
    url: https://www.example.com/contacts
  license:
    name: My License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: My local Fake Server
  - url: https://my-json-server.typicode.com/bearc0025/api/
    variables: {}
    description: My fake github server
  - url: www.example.com:{port}/{server}
    variables:
      port:
        default: '3000'
        enum:
          - '3000'
          - '3001'
        description: '3000: Dev , 3001: Prod'
      server:
        default: v3
        enum:
          - v3
          - v2
          - v1
        description: versions
    description: Fake server with variables
paths:
  /users:
    summary: users path level operations
    description: returns users from server, create a user, update or delete it.
    get:
      summary: fetch users from server
      description: return users
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: Add a new user
      description: Stores user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
  /attempts:
    summary: attempts path level operations
    description: returns attempts from server, create a attempt, update or delete it.
    get:
      summary: fetch attempts from server
      description: return attempts
      operationId: fetchAttempts
      responses:
        '200':
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - attempts
  /users/{userId}:
    summary: 'individuals user operation '
    description: fetch, delete, update an individuals user
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          example: 1234abc
    get:
      summary: fetch a user
      description: return a user from the server
      operationId: fetchUser
      responses:
        '200':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
components:
  responses:
    UserRespBody:
      description: success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
    UserArrayResponseBody:
      description: success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
  requestBodies:
    UserPostBody:
      description: new user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserPostBody'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    UserPostBody:
      type: object
      properties:
        username:
          type: string
          example: vikasm
        score:
          type: integer
          example: 1234
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - $ref: '#/components/schemas/UserPostBody'
        - type: object
          properties:
            id:
              type: string
              example: 1234abcd
